services:
  rabbitmq:
    image: rabbitmq:3-management
    # container_name: ms_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_NODE_IP_ADDRESS: 0.0.0.0
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  db: 
    image: postgres:15-alpine
    # container_name: ms_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: orders_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432" # Opcional: para acessar o banco de fora do Docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-net
    healthcheck: # <-- MELHORIA: Verifica se o banco está pronto para aceitar conexões.
      test: ["CMD-SHELL", "pg_isready -U admin -d orders_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  users:
    build:
      context: .                     # << agora é a raiz do projeto
      dockerfile: ./services/users-service/Dockerfile
    # container_name: ms_users
    restart: always
    environment:
      PORT: 3001
      DATABASE_URL: "file:./dev.db"
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      EXCHANGE: app.topic
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "3001:3001"
    networks: 
      - microservices-net
    healthcheck: # <-- MELHORIA: Garante que o serviço está no ar antes que outros dependam dele.
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  orders:
    build:
      context: .                     # << agora é a raiz do projeto
      dockerfile: ./services/orders-service/Dockerfile
    # container_name: ms_orders
    restart: always
    environment:
      PORT: 3002
      USERS_BASE_URL: http://users:3001
      HTTP_TIMEOUT_MS: 2000
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      EXCHANGE: app.topic
      QUEUE: orders.q
      ROUTING_KEY_USER_CREATED: user.created
      DATABASE_URL: postgres://admin:admin@db:5432/orders_db
    depends_on:
      rabbitmq:
        condition: service_started
      users:
        condition: service_healthy
      db:
        condition: service_healthy
    ports:
      - "3002:3002"
    networks: 
      - microservices-net
    healthcheck: # <-- MELHORIA
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    # container_name: ms_gateway
    restart: always
    environment:
      PORT: 3000
      USERS_URL: http://users:3001
      ORDERS_URL: http://orders:3002
    depends_on:
      users:
        condition: service_healthy
      orders:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks: 
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres_data:
  